apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-service
spec:
  type: NodePort
  selector:
    name: python-fastapi
  ports:
    - name: python-fastapi-service-port
      protocol: TCP
      port: 80
      targetPort: container-port
      nodePort: 30080
